# Generated by Django 5.1.2 on 2024-11-12 18:24

import django.db.models.deletion
import mptt.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('address', models.CharField(max_length=100, verbose_name='მისამართი')),
                ('phone', models.CharField(max_length=9, verbose_name='ტელეფონის ნომერი')),
                ('cover', versatileimagefield.fields.VersatileImageField(blank=True, help_text='ატვირთეთ ფოტოსურათი', null=True, upload_to='', verbose_name='გარეკანის ფოტოსურათი')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='სახელი')),
                ('cover', versatileimagefield.fields.VersatileImageField(blank=True, help_text='ატვირთეთ ფოტოსურათი', null=True, upload_to='', verbose_name='გარეკანის ფოტოსურათი')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='restaurant.category', verbose_name='ზეკატეგორია')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='სახელი')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='ატვირთეთ ფოტოსურათი', null=True, upload_to='', verbose_name='კერძის ფოტოსურათი')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='ფასი')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.category', verbose_name='კატეგორია')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='სახელი')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.dish', verbose_name='კერძი')),
            ],
        ),
    ]
