# Generated by Django 5.1.2 on 2024-11-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(verbose_name='ფასი'),
        ),
    ]
