# Generated by Django 5.1.2 on 2024-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(related_name='menus', to='restaurant.dish', verbose_name='კერძი'),
        ),
    ]
