# Generated by Django 5.1.2 on 2024-11-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_category_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
