# Generated by Django 5.1.2 on 2024-11-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
    ]
