# Generated by Django 5.1.2 on 2024-11-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_ingredient_dish_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.dish', verbose_name='კერძი'),
        ),
    ]
