# Generated by Django 5.1.2 on 2024-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_category_user_dish_user_ingredient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='restaurant.ingredient', verbose_name='ინგრედიენტები'),
        ),
    ]
