# Generated by Django 5.1.2 on 2024-11-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_remove_ingredient_dish_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='სახელი'),
        ),
    ]
