# Generated by Django 5.1.2 on 2024-11-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
