# Generated by Django 5.1.2 on 2024-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_remove_category_user_remove_dish_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.ingredient', verbose_name='ინგრედიენტები'),
        ),
    ]
